linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
